services:
  indiekit:
    build: .
    container_name: indiekit
    restart: unless-stopped
    env_file:
      - .env
    # network_mode: host # Bypass Docker Networking # use ports instead
    ports:
      - "8822:3000"
    environment:
      - NODE_ENV=production