services:
  indiekit:
    build: .
    container_name: indiekit
    restart: unless-stopped
    env_file:
      - .env
    network_mode: host # Bypass Docker Networking
    environment:
      - NODE_ENV=production